development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("HEROKU_REDIS_YELLOW_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails_project_production
